name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
      redis:
        image: redis:6.0
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install dependancies
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run black --check .
          poetry run isort -c .
          poetry run mypy .
          poetry run flake8
      - name: Test
        run: |
          poetry run pytest
